/*
 * Copyright 2018 Nicholas Harris
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
 *  to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
 *  and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS
 * OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 *  OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.scarabcoder.spaceraiders.player


import com.scarabcoder.spaceraiders.data.DataManager
import com.scarabcoder.spaceraiders.ship.Hangar
import com.scarabcoder.spaceraiders.ship.state.ShipState
import net.md_5.bungee.api.ChatMessageType
import net.md_5.bungee.api.chat.TextComponent
import org.bukkit.Bukkit
import org.bukkit.Location
import org.bukkit.OfflinePlayer
import org.bukkit.entity.Player
import java.util.*

/**
 * Created by owner on 1/5/2018.
 */
class SRPlayer(val uuid: UUID, var username: String, var squadID: Int?)  {

    var cached = false
    var cachedTime = System.currentTimeMillis()

    val isOnline: Boolean
        get() = Bukkit.getPlayer(uuid) == null

    val offlinePlayer: OfflinePlayer
        get() = Bukkit.getOfflinePlayer(uuid)

    val player: Player
        get() = Bukkit.getPlayer(uuid)

    val squad: Squad?
        get() = if(squadID == null) null else DataManager.getSquad(squadID!!)

    val privateHangar: Hangar
        get() = DataManager.autoGeneratedHangars.first { it.owner == uuid }

    var currentShipState: ShipState? = null
        get() = DataManager.activeShips.find { it.state.members.contains(this) }?.state

    var preStateLocation: Location = player.location

    fun sendMessage(message: String) = player.spigot().sendMessage(*TextComponent.fromLegacyText(message))

    fun sendActionBar(message: String) = player.spigot().sendMessage(ChatMessageType.ACTION_BAR, *TextComponent.fromLegacyText(message))

    override fun hashCode(): Int {
        return uuid.hashCode()
    }

    companion object {

        fun from(username: String): SRPlayer? {
            return DataManager.getPlayer(username)
        }

        fun from(player: Player): SRPlayer {
            return DataManager.getPlayer(player.uniqueId)
        }

        fun createTable(): String {
            return "CREATE TABLE IF NOT EXISTS players (" +
                    "uuid VARCHAR(36) NOT NULL PRIMARY KEY, " +
                    "username VARCHAR(16) NOT NULL, " +
                    "squad INT);"
        }
    }

}